version: "3"
services:
  {{ cookiecutter.svc_name }}:
    build: .
    ports:
    - "{{ cookiecutter.port}}:{{ cookiecutter.port}}"
    command: "/venv/bin/python /{{ cookiecutter.svc_name }}/manage.py runserver 0.0.0.0:{{ cookiecutter.port }}"
