---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ "{{" }}.Values.ingress.name{{ "}}" }}
  namespace: sre
spec:
  rules:
  - host: {{ "{{" }}.Values.ingress.host {{ "}}" }}
    http:
      paths:
      - backend:
          serviceName: {{ "{{" }}.Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}
          servicePort: 80
        path: /
