---
kind: Service
apiVersion: v1
metadata:
  name: {{ "{{" }} .Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}
  labels:
    k8s-app: {{ "{{" }} .Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}
    ingress.unity3d.com/haproxy: haproxy
  annotations:
    prometheus.io/name: {{ "{{" }} .Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}
    prometheus.io/port: {{ "{{" }} .Values.service.prometheus_port {{ "}}" }}
    prometheus.io/scrape: 'true'
    prometheus.io/probe: 'true'
    prometheus.io/path: '/metrics'
    dns.unity3d.com/domain: {{ "{{" }} .Values.service.domain {{ "}}" }}
    dns.unity3d.com/hostname: {{ "{{" }} .Values.service.kube53_name {{ "}}" }}
    dns.unity3d.com/class: route53
    dns.unity3d.com/type: private
spec:
  selector:
    app: {{ "{{" }} .Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP