{{ cookiecutter.svc_name }}:
  name: {{ cookiecutter.svc_name }}
  environment: dev
  resources:
    requests:
      cpu: "250m"
      memory: 50Mi
    limits:
      cpu: "500m"
      memory: 250Mi
ingress:
  host: {{ cookiecutter.svc_name }}.minikube.local
  name: {{ cookiecutter.svc_name }}-minikube-local
service:
  kube53_name: {{ cookiecutter.svc_name }}
  domain: minukube.local
