apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: sre
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.name }}
  selector:
    app: {{ .Values.name }}
